E1 = api
E2 = setjmp_ucontext

all:
	@echo "Compiling modules for Exercise 2"
	@cd $(E1); make;
	@cd $(E2); make;
	@echo "Compilation done."

clean:
	@echo "Cleaning modules for Exercise 2"
	@cd $(E1); make clean;
	@cd $(E2); make clean;
	@echo "Cleaning done."