	E1 = multi-task-scheduling

all:
	@echo "Compiling modules for Exercise 3"
	@cd $(E1); make;
	@echo "Compilation done."
		
clean:
	@echo "Cleaning modules for Exercise 3"
	@cd $(E1); make clean;
	@echo "Cleaning done."