	E1 = thread-object-lists

all:
	@echo "Compiling modules for Exercise 4"
	@cd $(E1); make;
	@echo "Compilation done."
		
clean:
	@echo "Cleaning modules for Exercise 4"
	@cd $(E1); make clean;
	@echo "Cleaning done."