E1 = user_space_scheduling

all:
	@echo "Compiling modules for Exercise 2"
	@cd $(E1); make;
	@echo "Compilation done."
	@echo "src/user_space_scheduling/api  - contains task API headers and implementation"
	@echo "src/user_space_scheduling/api/fibo - Fibonacci example"
	@echo "src/user_space_scheduling/api/printer - Print strings example"
	@echo "src/user_space_scheduling/setjmp_ucontext - Benchmarking between setjmp and ucontext"
	@echo "src/user_space_scheduling/setjmp_ucontext/setjmp_test - Alternate jump tests for setjmp"
	@echo "src/user_space_scheduling/setjmp_ucontext/ucontext_test- Alternate jump tests for ucontext"
	@echo "src/user_space_scheduling/setjmp_ucontext/test_timing - Simple test for setjmp and ucontext"
	
clean:
	@echo "Cleaning modules for Exercise 2"
	@cd $(E1); make clean;
	@echo "Cleaning done."