E1 = user_space_scheduling

all:
	@echo "Compiling modules for Exercise 2"
	@cd $(E1); make;
	@echo "Compilation done."

clean:
	@echo "Cleaning modules for Exercise 2"
	@cd $(E1); make clean;
	@echo "Cleaning done."